"""empty message

Revision ID: 16ed81b0da41
Revises: 62163e59eacc
Create Date: 2016-05-17 20:04:41.983006

"""

# revision identifiers, used by Alembic.
revision = '16ed81b0da41'
down_revision = '62163e59eacc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_filename', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'image_filename')
    ### end Alembic commands ###
